AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an EC2 instance."
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: eu-central-1a
            ImageId: ami-01f79b1e4a5c64257
            InstanceType: t3.micro